variables:
  port: "8080"
  container_name: "authbitreader_dev_$CI_COMMIT_SHORT_SHA"
  image_tag: $CI_REGISTRY_IMAGE/dev:$container_name
  image_tag_latest: $CI_REGISTRY_IMAGE/dev:latest

stages:
  - build
  - prepare
  - deploy

build-job:
  only:
    - deploy/dev
  image: openjdk:latest
  artifacts:
      paths:
        - build/quarkus-app
  stage: build
  before_script:
    - chmod +x ./gradlew 
    - cp $application_properties src/main/resources/
    - rm src/main/resources/application.properties
    - mv src/main/resources/application_properties src/main/resources/application.properties
    - cp $public_key src/main/resources/ && mv src/main/resources/public_key src/main/resources/publickey.pem
    - cp $private_key src/main/resources/ && mv src/main/resources/private_key src/main/resources/privatekey.pem
  script:
    - ./gradlew build


create-docker-image-job:
  tags:
    - docker
  only:
    - deploy/dev
  stage: prepare
  script:
    - echo $image_tag
    - docker login -u $CI_REGISTRY_USER -p $personal_access_token $CI_REGISTRY
    - docker build -f src/main/docker/Dockerfile.jvm -t $image_tag -t $image_tag_latest . 
    - docker push $image_tag && docker push $image_tag_latest


deploy-job:
  stage: deploy
  only:
    - deploy/dev
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p ~/.ssh && touch ~/.ssh/config
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - echo "$deploy_server_ssh_private_key" | tr -d '\r' | ssh-add -
    - cat $deploy_server_ssh_config >> ~/.ssh/config
  script:
    - ssh deploy -o StrictHostKeyChecking=no "curl $check_port_script_link > check_port.sh && chmod +x check_port.sh && bash check_port.sh $port"
    - ssh deploy -o StrictHostKeyChecking=no "docker login -u $CI_REGISTRY_USER -p $personal_access_token $CI_REGISTRY && docker pull $image_tag_latest && docker run -d -p $port:$port -e QUARKUS_LAUNCH_DEVMODE=true --restart=always --network=nginx --name $container_name $image_tag_latest"
